receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 2s
    limit_mib: 512
    spike_limit_mib: 128

  batch:
    timeout: 2s
    send_batch_size: 1024
    send_batch_max_size: 2048

  attributes/add_common:
    actions:
      - key: ops.stack
        value: "jimbo77-observability"
        action: insert

  # Sampling (opcjonalnie): 100% na start, potem zmienisz na np. 20
  probabilistic_sampler:
    sampling_percentage: 100

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  # Debug (opcjonalnie): loguje spany w logach collectora
  logging:
    verbosity: basic

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

  pprof:
    endpoint: 0.0.0.0:1888

service:
  extensions: [health_check, pprof]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, attributes/add_common, probabilistic_sampler, batch]
      exporters: [otlp/tempo]
