
import asyncio
import aiohttp
import argparse
import os
import re
import subprocess
import time
from datetime import datetime

# Logic configuration
BLOG_REPO_DIR = r"U:\The_yellow_hub\my-bonzo-ai-blog"
BLOG_CONTENT_DIR = os.path.join(BLOG_REPO_DIR, r"src\content\posts")

# Agent endpoints
WRITER_AGENT_URL = "http://localhost:6030/api"
RESEARCH_AGENT_URL = "http://localhost:6062/api"
SEO_AGENT_URL = "http://localhost:6031/api"

async def call_agent(url: str, data: dict) -> str:
    """Generic agent caller"""
    async with aiohttp.ClientSession() as session:
        try:
            async with session.post(url, json={"action": "execute", "data": data}) as response:
                if response.status != 200:
                    return f"Error: {await response.text()}"
                result = await response.json()
                return result.get("data", {}).get("content", "")
        except Exception as e:
            return f"Error connection: {e}"

async def brainstorm_and_publish(category: str):
    """Full pipeline: Research -> SEO -> Write -> Publish"""
    print(f"\n🧠 BRAINSTORMING MODE: '{category}'")
    
    # 1. Research Trends
    print("🔍 [1/4] Researching Trends...")
    trends = await call_agent(RESEARCH_AGENT_URL, {
        "type": "trends", 
        "query": category
    })
    if "Error" in trends:
        print(f"❌ Research failed: {trends}")
        return
        
    print(f"   ✅ Found trends: {trends[:100]}...")
    
    # 2. Extract best topic
    print("🎯 [2/4] Selecting Topic...")
    topic_selection_prompt = f"Based on these trends, suggest ONE specific, catchy blog post title about {category}:\n{trends}"
    title_response = await call_agent(WRITER_AGENT_URL, {
        "type": "content", 
        "prompt": topic_selection_prompt,
        "style": "concise"
    })
    
    # Clean title: Take first non-empty line, remove quotes and "Title:" prefix
    title_lines = [line.strip() for line in title_response.split('\n') if line.strip()]
    title = title_lines[0] if title_lines else "New Blog Post"
    title = title.replace('"', '').replace("Title:", "").replace("**", "").strip()
    
    print(f"   🏆 Topic: {title}")
    
    # 3. SEO Keywords
    print("🚀 [3/4] Analyzing SEO...")
    keywords = await call_agent(SEO_AGENT_URL, {
        "type": "keywords",
        "query": title
    })
    
    # 4. Generate Content
    print(f"📝 [4/4] Writing & Publishing...")
    final_prompt = f"""
    Title: {title}
    Context/Trends: {trends[:400]}
    SEO Keywords: {keywords[:400]}
    
    IMPORTANT INSTRUCTIONS:
    1. DO NOT use citation numbers like [1], [2], [3]. Remove them completely.
    2. Write naturally as a human expert.
    """
    await generate_post(final_prompt, title, style="professional", auto_deploy=True)


async def generate_post(prompt: str, topic: str, style: str = "professional", auto_deploy: bool = False):
    """Call Writer Agent to generate post and optionally deploy"""
    print(f"🚀 Generating Article for: '{topic}'")
    
    # Ensure prompt includes "No citations" instruction
    if "DO NOT use citation" not in prompt:
         prompt += "\n\nCRITICAL: DO NOT include citation numbers like [1] or [2] in the text."

    content = await call_agent(WRITER_AGENT_URL, {
        "type": "seo",
        "prompt": prompt,
        "style": style
    })
    
    if "Error" in content or not content:
        print(f"❌ Failed: {content}")
        return

    print("✅ Content generated!")
    filepath = save_post(topic, content)
    
    if filepath and auto_deploy:
        deploy_to_git(filepath)
        social_blast(topic, f"https://mybonzoaiblog.com/{os.path.basename(filepath).replace('.md','')}")

def save_post(topic: str, content: str):
    """Save content to blog directory with frontmatter"""
    safe_topic = topic[:50]
    slug = re.sub(r'[^a-z0-9]+', '-', safe_topic.lower()).strip('-')
    filename = f"{slug}.md"
    filepath = os.path.join(BLOG_CONTENT_DIR, filename)
    
    os.makedirs(BLOG_CONTENT_DIR, exist_ok=True)
    
    # 1. Clean Markdown Code Blocks
    content = content.replace("```markdown", "").replace("```", "").strip()
    
    # 2. Clean Citation Markers [1], [2], [12] using Regex
    content = re.sub(r'\[\d+(?:,\s*\d+)*\]', '', content)
    
    # 3. Branding Footer (Meble Pumo & My Bonzo AI)
    branding_footer = "\n\n---\n\n_Wsparcie merytoryczne: [My Bonzo AI](https://mybonzo.ai) | Partnerzy: [Meble Pumo](https://pumo.pl)_"
    
    # Add Frontmatter if not present
    if not content.startswith("---"):
        date_str = datetime.now().strftime("%Y-%m-%d")
        frontmatter = f"""---
title: "{topic[:80].replace('"', '')}"
description: "Generated by JIMBO Publisher 2.0 (MOA Powered)"
pubDate: "{date_str}"
category: "AI"
author: "Pumo AI"
tags: ["ai", "tech", "automation"]
---

"""
        content = frontmatter + content + branding_footer
    else:
        # If frontmatter exists, just append footer
        content = content + branding_footer
    
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"💾 Saved to: {filepath}")
        return filepath
    except Exception as e:
        print(f"❌ Failed to save file: {e}")
        return None

def deploy_to_git(filepath):
    """Git Add/Commit/Push"""
    print(f"📦 Deploying to Repository: {BLOG_REPO_DIR}")
    try:
        # Check if it's a git repo
        if not os.path.exists(os.path.join(BLOG_REPO_DIR, ".git")):
            print("⚠️ Not a git repository. Skipping deployment.")
            return

        filename = os.path.basename(filepath)
        
        # Git Add
        subprocess.run(["git", "add", filepath], cwd=BLOG_REPO_DIR, check=True, capture_output=True)
        
        # Git Commit
        msg = f"New Content: {filename} (via Jimbo Publisher)"
        subprocess.run(["git", "commit", "-m", msg], cwd=BLOG_REPO_DIR, check=True, capture_output=True)
        
        # Git Push
        print("☁️ Pushing to Cloudflare Pages (Origin)...")
        subprocess.run(["git", "push"], cwd=BLOG_REPO_DIR, check=True, capture_output=True)
        
        print(f"✅ Successfully Deployed: {filename}")
        
    except subprocess.CalledProcessError as e:
        print(f"❌ Git Error: {e}")

def social_blast(title, url):
    """Simulate Social Media Posting"""
    print("\n📣 --- SOCIAL BLAST (Simulation) ---")
    print(f"🐦 [Twitter] New post! '{title}' read here: {url} #AI #Tech")
    print(f"💼 [LinkedIn] Insights on '{title}'. Check it out: {url}")
    print("---------------------------------------")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="JIMBO Publisher Ultimate (MOA + Git)")
    parser.add_argument("--topic", type=str, help="Specific topic (Direct Write)")
    parser.add_argument("--brainstorm", type=str, help="Category to brainstorm (Research -> SEO -> Write)")
    parser.add_argument("--style", type=str, default="professional", help="Writing style")
    parser.add_argument("--deploy", action="store_true", help="Auto deploy to Git")
    
    args = parser.parse_args()
    
    if args.brainstorm:
        asyncio.run(brainstorm_and_publish(args.brainstorm))
    elif args.topic:
        asyncio.run(generate_post(args.topic, args.topic, args.style, args.deploy))
    else:
        print("Usage: python publisher_workflow.py --brainstorm 'AI' OR --topic 'My Topic' [--deploy]")
